version: 0.2

phases:
  install:
    commands:
      # Install OpenJDK 17 or Amazon Corretto
      - echo "Installing Amazon Corretto OpenJDK 17..."
      - yum install -y java-17-amazon-corretto-devel  # Attempt to install Corretto JDK 17
      - echo "Setting JAVA_HOME..."
      - export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
      - export JRE_HOME=$JAVA_HOME
      - export JDK_HOME=$JAVA_HOME

  build:
    commands:
      - echo "Building the application..."
      - mvn clean install  # Replace with your own build commands if needed

  post_build:
    commands:
      - echo "Post build steps here..."

artifacts:
  files:
    - target/*.jar  # Replace with your artifact paths
